### Content Based Recommendations

In the previous notebook, you were introduced to a way of making recommendations using collaborative filtering.  However, using this technique there are a large number of users who were left without any recommendations at all.  Other users were left with fewer than the ten recommendations that were set up by our function to retrieve....

In order to help these users out, let's try another technique: **content based** recommendations. Let's start off where we were in the previous notebook.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict
from IPython.display import HTML
import progressbar
import tests as t
import pickle


%matplotlib inline

# Read in the datasets
movies = pd.read_csv('movies_clean.csv')
reviews = pd.read_csv('reviews_clean.csv')

del movies['Unnamed: 0']
del reviews['Unnamed: 0']


all_recs = pickle.load(open("all_recs.p", "rb"))

### Datasets

From the above, you now have access to three important items that you will be using throughout the rest of this notebook.  

`a.` **movies** - a dataframe of all of the movies in the dataset along with other content related information about the movies (genre and date)


`b.` **reviews** - this was the main dataframe used before for collaborative filtering, as it contains all of the interactions between users and movies.


`c.` **all_recs** - a dictionary where each key is a user, and the value is a list of movie recommendations based on collaborative filtering

For the individuals in **all_recs** who did receive 10 recommendations using collaborative filtering, we don't really need to worry about them.  However, there were a number of individuals in our dataset who did not receive any recommendations.

-----

`1.` Let's start with finding all of the users in our dataset who didn't get all 10 ratings we would have liked them to have using collaborative filtering.

In [2]:
users_with_all_recs = [] # Store user ids who have all their recommendations in this (10 or more)
users_who_need_recs = [] # Store users who still need recommendations here

for key, value in all_recs.items():
    if len(value) >= 10:
        users_with_all_recs.append(key)

users_who_need_recs = list(set(reviews['user_id'].unique().tolist()) - set(users_with_all_recs))

In [3]:
len(users_who_need_recs)

31781

In [4]:
len(users_with_all_recs)

22187

In [3]:
# A quick test
assert len(users_with_all_recs) == 22187
print("That's right there were still another 31781 users who needed recommendations when we only used collaborative filtering!")

That's right there were still another 31781 users who needed recommendations when we only used collaborative filtering!

### Content Based Recommendations

You will be doing a bit of a mix of content and collaborative filtering to make recommendations for the users this time.  This will allow you to obtain recommendations in many cases where we didn't make recommendations earlier.     

`2.` Before finding recommendations, rank the user's ratings from highest to lowest. You will move through the movies in this order looking for other similar movies.

In [4]:
# create a dataframe similar to reviews, but ranked by rating for each user
reviews_rating_ranked = reviews.sort_values(['user_id', 'rating'],  ascending=[True, False])

In [5]:
reviews_rating_ranked.head(5)

,user_id,movie_id,rating,timestamp,date,month_1,month_2,month_3,month_4,month_5,...,month_9,month_10,month_11,month_12,year_2013,year_2014,year_2015,year_2016,year_2017,year_2018
0,1,68646,10,1381620027,2013-10-12 23:20:27,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
1,1,113277,10,1379466669,2013-09-18 01:11:09,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
16,2,1798709,10,1389948338,2014-01-17 08:45:38,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
18,2,2024544,10,1389355949,2014-01-10 12:12:29,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
22,2,2726560,9,1438293988,2015-07-30 22:06:28,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

### Similarities

In the collaborative filtering sections, you became quite familiar with different methods of determining the similarity (or distance) of two users.  We can perform similarities based on content in much the same way.  

In many cases, it turns out that one of the fastest ways we can find out how similar items are to one another (when our matrix isn't totally sparse like it was in the earlier section) is by simply using matrix multiplication.  If you are not familiar with this, an explanation is available [here by 3blue1brown](https://www.youtube.com/watch?v=LyGKycYT2v0) and another quick explanation is provided [in the post here](https://math.stackexchange.com/questions/689022/how-does-the-dot-product-determine-similarity).

For us to pull out a matrix that describes the movies in our dataframe in terms of content, we might just use the indicator variables related to **year** and **genre** for our movies.  

Then we can obtain a matrix of how similar movies are to one another by taking the dot product of this matrix with itself.  Notice below that the dot product where our 1 values overlap gives a value of 2 indicating higher similarity.  In the second dot product, the 1 values don't match up.  This leads to a dot product of 0 indicating lower similarity.

<img src="images/dotprod1.png" alt="Dot Product" height="500" width="500">

We can perform the dot product on a matrix of movies with content characteristics to provide a movie by movie matrix where each cell is an indication of how similar two movies are to one another.  In the below image, you can see that movies 1 and 8 are most similar, movies 2 and 8 are most similar, and movies 3 and 9 are most similar for this subset of the data.  The diagonal elements of the matrix will contain the similarity of a movie with itself, which will be the largest possible similarity (and will also be the number of 1's in the movie row within the orginal movie content matrix).

<img src="images/moviemat.png" alt="Dot Product" height="500" width="500">


`3.` Create a numpy array that is a matrix of indicator variables related to year (by century) and movie genres by movie.  Perform the dot product of this matrix with itself (transposed) to obtain a similarity matrix of each movie with every other movie.  The final matrix should be 31245 x 31245.

In [6]:
# number of movies
movies.shape

(31245, 35)

In [7]:
movies.head(1)

,movie_id,movie,genre,date,1800's,1900's,2000's,History,News,Horror,...,Fantasy,Romance,Game-Show,Action,Documentary,Animation,Comedy,Short,Western,Thriller
0,8,Edison Kinetoscopic Record of a Sneeze (1894),Documentary|Short,1894,1,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0

In [11]:
np.array(movies.drop(['movie_id', 'movie', 'genre', 'date'], axis=1).head(3))

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 0]], dtype=int64)

In [8]:
# Subset so movie_content is only using the dummy variables for each genre and the 3 century based year dummy columns
movie_content = np.array(movies.drop(['movie_id', 'movie', 'genre', 'date'], axis=1))

# Take the dot product to obtain a movie x movie matrix of similarities
dot_prod_movies = np.dot(movie_content, np.transpose(movie_content))

In [51]:
movie_content[0]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0], dtype=int64)

In [52]:
dot_prod_movies[0, 0]

3

In [53]:
np.max(dot_prod_movies[0])

3

In [9]:
# create checks for the dot product matrix
assert dot_prod_movies.shape[0] == 31245
assert dot_prod_movies.shape[1] == 31245
assert dot_prod_movies[0, 0] == np.max(dot_prod_movies[0])
print("Looks like you passed all of the tests.  Though they weren't very robust - if you want to write some of your own, I won't complain!")

Looks like you passed all of the tests.  Though they weren't very robust - if you want to write some of your own, I won't complain!

### For Each User...


Now you have a matrix where each user has their ratings ordered.  You also have a second matrix where movies are each axis, and the matrix entries are larger where the two movies are more similar and smaller where the two movies are dissimilar.  This matrix is a measure of content similarity. Therefore, it is time to get to the fun part.

For each user, we will perform the following:

    i. For each movie, find the movies that are most similar that the user hasn't seen.

    ii. Continue through the available, rated movies until 10 recommendations or until there are no additional movies.

As a final note, you may need to adjust the criteria for 'most similar' to obtain 10 recommendations.  As a first pass, I used only movies with the highest possible similarity to one another as similar enough to add as a recommendation.

`3.` In the cell below, complete each of the functions needed for making content based recommendations.

In [259]:
dot_prod_movies

array([[3, 3, 3, ..., 0, 0, 0],
       [3, 3, 3, ..., 0, 0, 0],
       [3, 3, 3, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 2, 2, 1],
       [0, 0, 0, ..., 2, 2, 1],
       [0, 0, 0, ..., 1, 1, 2]], dtype=int64)

In [260]:
b = dot_prod_movies[1].copy()
b

array([3, 3, 3, ..., 0, 0, 0], dtype=int64)

In [262]:
b==3

array([ True,  True,  True, ..., False, False, False])

In [284]:
movies.head(4)

,movie_id,movie,genre,date,1800's,1900's,2000's,History,News,Horror,...,Fantasy,Romance,Game-Show,Action,Documentary,Animation,Comedy,Short,Western,Thriller
0,8,Edison Kinetoscopic Record of a Sneeze (1894),Documentary|Short,1894,1,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
1,10,La sortie des usines Lumière (1895),Documentary|Short,1895,1,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
2,12,The Arrival of a Train (1896),Documentary|Short,1896,1,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
3,25,The Oxford and Cambridge University Boat Race ...,NaN,1895,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [286]:
c = movies.loc[b==3]
c

,movie_id,movie,genre,date,1800's,1900's,2000's,History,News,Horror,...,Fantasy,Romance,Game-Show,Action,Documentary,Animation,Comedy,Short,Western,Thriller
0,8,Edison Kinetoscopic Record of a Sneeze (1894),Documentary|Short,1894,1,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
1,10,La sortie des usines Lumière (1895),Documentary|Short,1895,1,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
2,12,The Arrival of a Train (1896),Documentary|Short,1896,1,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
9584,154152,Annabelle Serpentine Dance (1895),Documentary|Short,1895,1,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
12766,392728,Roundhay Garden Scene (1888),Documentary|Short,1888,1,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
21723,2185694,Llandudno Happy Valley and Minstrel Show (1898),Documentary|Short,1898,1,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0

In [359]:
np.array(c[~c.index.isin([1])]['movie'])

array(['Edison Kinetoscopic Record of a Sneeze (1894)',
       'The Arrival of a Train (1896)',
       'Annabelle Serpentine Dance (1895)',
       'Roundhay Garden Scene (1888)',
       'Llandudno Happy Valley and Minstrel Show (1898)'], dtype=object)

In [258]:
movies.iloc[movies[movies['movie_id']==8].index[0]][:4]

movie_id                                                8
movie       Edison Kinetoscopic Record of a Sneeze (1894)
genre                                   Documentary|Short
date                                                 1894
Name: 0, dtype: object

In [38]:
movies['movie'].shape

(31245,)

In [14]:
def find_similar_movies(movie_id):
    '''
    INPUT
    movie_id - a movie_id 
    OUTPUT
    similar_movies - an array of the most similar movies by title
    '''
    # find the row of each movie id
    my_movie_row = movies[movies['movie_id'] == movie_id].index[0]
    
    # find the most similar movie indices - to start I said they need to be the same for all content
    similar_movies = dot_prod_movies[my_movie_row]
    # identify max value for most similar movies
    max_similarity = similar_movies[my_movie_row]
    # filter only for movies which have same simalirty value
    my_movies = movies[similar_movies==max_similarity]
    # remove the actual movie we are looking at
    my_movies = my_movies[~my_movies.index.isin([my_movie_row])]
    
    # pull the movie titles based on the indices
    similar_movies = my_movies['movie']    
    
    return list(similar_movies)

In [25]:
test = find_similar_movies(10)
test

['Edison Kinetoscopic Record of a Sneeze (1894)',
 'The Arrival of a Train (1896)',
 'Annabelle Serpentine Dance (1895)',
 'Roundhay Garden Scene (1888)',
 'Llandudno Happy Valley and Minstrel Show (1898)']

In [26]:
test2 = find_similar_movies(8)
test2

['La sortie des usines Lumière (1895)',
 'The Arrival of a Train (1896)',
 'Annabelle Serpentine Dance (1895)',
 'Roundhay Garden Scene (1888)',
 'Llandudno Happy Valley and Minstrel Show (1898)']

In [27]:
test.extend(test2)

In [28]:
test

['Edison Kinetoscopic Record of a Sneeze (1894)',
 'The Arrival of a Train (1896)',
 'Annabelle Serpentine Dance (1895)',
 'Roundhay Garden Scene (1888)',
 'Llandudno Happy Valley and Minstrel Show (1898)',
 'La sortie des usines Lumière (1895)',
 'The Arrival of a Train (1896)',
 'Annabelle Serpentine Dance (1895)',
 'Roundhay Garden Scene (1888)',
 'Llandudno Happy Valley and Minstrel Show (1898)']

In [29]:
# You made this function in an earlier notebook - using again here    
def get_movie_names(movie_ids):
    '''
    INPUT
    movie_ids - a list of movie_ids
    OUTPUT
    movies - a list of movie names associated with the movie_ids
    
    '''
    movie_lst = list(movies[movies['movie_id'].isin(movie_ids)]['movie'])
   
    return movie_lst

In [36]:
find_similar_movies(68646)

["Fantômas - À l'ombre de la guillotine (1913)",
 'Regeneration (1915)',
 'Schloß Vogeloed (1921)',
 'The Lodger: A Story of the London Fog (1927)',
 'Underworld (1927)',
 'Die Büchse der Pandora (1929)',
 'The Docks of New York (1928)',
 'The Big House (1930)',
 'Escape! (1930)',
 'Hogaraka ni ayume (1930)',
 'Little Caesar (1931)',
 'Sono yo no tsuma (1930)',
 'Daughter of the Dragon (1931)',
 'A Free Soul (1931)',
 'M (1931)',
 'Night Nurse (1931)',
 'Pardon Us (1931)',
 'The Public Enemy (1931)',
 'Safe in Hell (1931)',
 'Smart Money (1931)',
 'I Am a Fugitive from a Chain Gang (1932)',
 'The Impassive Footman (1932)',
 'Scarface (1932)',
 'Three on a Match (1932)',
 'Blondie Johnson (1933)',
 'Hijôsen no onna (1933)',
 'Picture Snatcher (1933)',
 'Jimmy the Gent (1934)',
 'Manhattan Melodrama (1934)',
 'Crime and Punishment (1935)',
 'Maria Marten, or The Murder in the Red Barn (1935)',
 'Adventure in Manhattan (1936)',
 'Les bas-fonds (1936)',
 'Le crime de Monsieur Lange (1936)',
 'The Crimes of Stephen Hawke (1936)',
 'Fury (1936)',
 'We Who Are About to Die (1937)',
 'Pépé le Moko (1937)',
 'The Ticket of Leave Man (1937)',
 'You Only Live Once (1937)',
 'Engelen met smerige gezichten (1938)',
 'Het dierlijke in de mens (1938)',
 'Le quai des brumes (1938)',
 'The Green Hornet (1940)',
 'Le jour se lève (1939)',
 'King of the Underworld (1939)',
 'The Roaring Twenties (1939)',
 "You Can't Get Away with Murder (1939)",
 'Crimes at the Dark House (1940)',
 'The House Across the Bay (1940)',
 'Invisible Stripes (1939)',
 'It All Came True (1940)',
 'Johnny Apollo (1940)',
 'The Letter (1940)',
 'Phantom of Chinatown (1940)',
 'Stranger on the Third Floor (1940)',
 'They Drive by Night (1940)',
 'A Date with the Falcon (1942)',
 'The Gay Falcon (1941)',
 'High Sierra (1941)',
 'I Wake Up Screaming (1941)',
 'The Maltese Falcon (1941)',
 'A Man Betrayed (1941)',
 'The Shanghai Gesture (1941)',
 "The Falcon's Brother (1942)",
 'The Glass Key (1942)',
 'Moontide (1942)',
 'Ossessione (1943)',
 'Sherlock Holmes and the Secret Weapon (1942)',
 'This Gun for Hire (1942)',
 'Le corbeau (1943)',
 'The Falcon Strikes Back (1943)',
 'The Falcon and the Co-eds (1943)',
 'Phantom Lady (1944)',
 'Le voyageur de la Toussaint (1943)',
 'Double Indemnity (1944)',
 'The Falcon in Hollywood (1944)',
 'Gaslight (1944)',
 'Laura (1944)',
 'The Mask of Dimitrios (1944)',
 'Ministry of Fear (1944)',
 'Murder, My Sweet (1944)',
 'Strangers in the Night (1944)',
 'The Woman in the Window (1944)',
 'And Then There Were None (1945)',
 'Danger Signal (1945)',
 'Detour (1945)',
 'Dillinger (1945)',
 'Hangover Square (1945)',
 'The House on 92nd Street (1945)',
 'Mildred Pierce (1945)',
 'The Shanghai Cobra (1945)',
 'A Close Call for Boston Blackie (1946)',
 'Criminal Court (1946)',
 'The Dark Corner (1946)',
 'The Dark Mirror (1946)',
 'Deception (1946)',
 'The Killers (1946)',
 'The Postman Always Rings Twice (1946)',
 'Somewhere in the Night (1946)',
 'The Stranger (1946)',
 'The Verdict (1946)',
 'Born to Kill (1947)',
 'Brighton Rock (1947)',
 'Brute Force (1947)',
 'The Chinese Ring (1947)',
 'Crossfire (1947)',
 'Dead Reckoning (1947)',
 'Dear Murderer (1947)',
 'A Double Life (1947)',
 'Framed (1947)',
 'The Gangster (1947)',
 'I Walk Alone (1948)',
 "Johnny O'Clock (1947)",
 'Kus des doods (1947)',
 'Monsieur Verdoux (1947)',
 'Odd Man Out (1947)',
 'Out of the Past (1947)',
 'The Paradine Case (1947)',
 'Possessed (1947)',
 'Repeat Performance (1947)',
 'They Made Me a Fugitive (1947)',
 'The Unfaithful (1947)',
 'The Upturned Glass (1947)',
 'The Big Clock (1948)',
 'Cry of the City (1948)',
 'Force of Evil (1948)',
 'The Hunted (1948)',
 'Key Largo (1948)',
 'The Lady from Shanghai (1947)',
 'Moonrise (1948)',
 'The Naked City (1948)',
 'Oliver Twist (1948)',
 'Raw Deal (1948)',
 'Rope (1948)',
 'Salón México (1949)',
 'Snowbound (1948)',
 'Yoidore tenshi (1948)',
 'The Bribe (1949)',
 'Follow Me Quietly (1949)',
 'House of Strangers (1949)',
 'Mr. Soft Touch (1949)',
 'Nora inu (1949)',
 'Port of New York (1949)',
 'The Reckless Moment (1949)',
 'Red Light (1949)',
 'Shockproof (1949)',
 'Too Late for Tears (1949)',
 'Under Capricorn (1949)',
 'Whirlpool (1949)',
 'White Heat (1949)',
 '711 Ocean Drive (1950)',
 'The Asphalt Jungle (1950)',
 'The Blue Lamp (1950)',
 'The Breaking Point (1950)',
 'Cronaca di un amore (1950)',
 "The Damned Don't Cry (1950)",
 'Deadly Is the Female (1950)',
 'A Lady Without Passport (1950)',
 'Madeleine (1950)',
 'No Way Out (1950)',
 'Los olvidados (1950)',
 'Quicksand (1950)',
 'Rashômon (1950)',
 'Side Street (1949)',
 'The Sound of Fury (1950)',
 'Where the Sidewalk Ends (1950)',
 'Woman on the Run (1950)',
 "Casque d'or (1952)",
 'Cause for Alarm! (1951)',
 'Cry Danger (1951)',
 'Detective Story (1951)',
 'The Fat Man (1951)',
 'Golden Salamander (1950)',
 'Een der daders ontkwam (1951)',
 'The Hoodlum (1951)',
 'Lightning Strikes Twice (1951)',
 'The Man with a Cloak (1951)',
 'On Dangerous Ground (1951)',
 "The People Against O'Hara (1951)",
 'Misdaad N.V. (1951)',
 'The Tall Target (1951)',
 'Affair in Trinidad (1952)',
 'Angel Face (1952)',
 "Another Man's Poison (1951)",
 'The Captive City (1952)',
 'Cosh Boy (1953)',
 'Deadline - U.S.A. (1952)',
 'Home at Seven (1952)',
 'Kansas City Confidential (1952)',
 'The Last Page (1952)',
 'The Steel Trap (1952)',
 'One Way Ticket to Hell (1955)',
 '99 River Street (1953)',
 'The Blue Gardenia (1953)',
 'The Glass Web (1953)',
 'Mantrap (1953)',
 'La môme vert de gris (1953)',
 'Split Second (1953)',
 'Touchez pas au grisbi (1954)',
 'Turn the Key Softly (1953)',
 'The Barefoot Contessa (1954)',
 'Crime Wave (1954)',
 'The Fast and the Furious (1955)',
 'An Inspector Calls (1954)',
 'On the Waterfront (1954)',
 'Pushover (1954)',
 'Riot in Cell Block 11 (1954)',
 'Shield for Murder (1954)',
 'Suddenly (1954)',
 'Witness to Murder (1954)',
 'Bad Day at Black Rock (1955)',
 'The Big Combo (1955)',
 'Blackboard Jungle (1955)',
 'Bob le flambeur (1956)',
 'A Bullet for Joey (1955)',
 'The Desperate Hours (1955)',
 'Ensayo de un crimen (1955)',
 'The Green Buddha (1955)',
 'House of Bamboo (1955)',
 "Killer's Kiss (1955)",
 'Mr. Arkadin (1955)',
 'Muerte de un ciclista (1955)',
 'The Night of the Hunter (1955)',
 'The Phenix City Story (1955)',
 'Razzia sur la Chnouf (1955)',
 'Shree 420 (1955)',
 'Violent Saturday (1955)',
 'The Bad Seed (1956)',
 'Beyond a Reasonable Doubt (1956)',
 'A Cry in the Night (1956)',
 'The Killer Is Loose (1956)',
 'The Killing (1956)',
 'Man in the Vault (1956)',
 'Please Murder Me! (1956)',
 'Ransom! (1956)',
 'A Town Like Alice (1956)',
 'While the City Sleeps (1956)',
 '12 Angry Men (1957)',
 'Across the Bridge (1957)',
 'Crime of Passion (1957)',
 'Curfew Breakers (1957)',
 'Love in the Afternoon (1957)',
 'Porte des Lilas (1957)',
 "Ascenseur pour l'échafaud (1958)",
 'Bab el hadid (1958)',
 'The Defiant Ones (1958)',
 'Es geschah am hellichten Tag (1958)',
 "Gideon's Day (1958)",
 'Hell Drivers (1957)',
 'I Want to Live! (1958)',
 'Kagenaki koe (1958)',
 'King Creole (1958)',
 'The Left Handed Gun (1958)',
 'The Lineup (1958)',
 "The Man Who Wouldn't Talk (1958)",
 'Thunder Road (1958)',
 'The True Story of Lynn Stuart (1958)',
 'Anatomy of a Murder (1959)',
 'The Bloody Brood (1959)',
 'Compulsion (1959)',
 'Deux hommes dans Manhattan (1959)',
 'Edge of Eternity (1959)',
 'The Flesh and the Fiends (1960)',
 'Odds Against Tomorrow (1959)',
 'Pickpocket (1959)',
 'Les quatre cents coups (1959)',
 'Sapphire (1959)',
 'The 39 Steps (1959)',
 'À bout de souffle (1960)',
 'Our Man in Havana (1959)',
 'Rocco e i suoi fratelli (1960)',
 'Tirez sur le pianiste (1960)',
 'Le trou (1960)',
 'Warui yatsu hodo yoku nemuru (1960)',
 'Blast of Silence (1961)',
 'Buta to gunkan (1961)',
 'Cash on Demand (1961)',
 'A Matter of WHO (1961)',
 'Murder She Said (1961)',
 'An einem Freitag um halb zwölf (1961)',
 'Town Without Pity (1961)',
 'Underworld U.S.A. (1961)',
 'Victim (1961)',
 'West Side Story (1961)',
 'La commare secca (1962)',
 'Mafioso (1962)',
 'Das indische Tuch (1963)',
 'Murder at the Gallop (1963)',
 'The Prize (1963)',
 'Tengoku to jigoku (1963)',
 'Bande à part (1964)',
 'Dead Ringer (1964)',
 'Deus e o Diabo na Terra do Sol (1964)',
 "Le journal d'une femme de chambre (1964)",
 'Murder Most Foul (1964)',
 'The Naked Kiss (1964)',
 'Nikutai no mon (1964)',
 'Seance on a Wet Afternoon (1964)',
 'La donna del lago (1965)',
 'Etsuraku (1965)',
 'Pierrot le fou (1965)',
 'The Chase (1966)',
 'Le deuxième souffle (1966)',
 'Hakuchû no tôrima (1966)',
 'Harper (1966)',
 'Objectif: 500 millions (1966)',
 'The Quiller Memorandum (1966)',
 'Rosalie (1966)',
 'Svegliati e uccidi (1966)',
 'Tôkyô nagaremono (1966)',
 'Accident (1967)',
 'Bonnie and Clyde (1967)',
 'Cool Hand Luke (1967)',
 'Hells Angels on Wheels (1967)',
 'In Cold Blood (1967)',
 'In the Heat of the Night (1967)',
 'The Incident (1967)',
 'Jewel Thief (1967)',
 'Koroshi no rakuin (1967)',
 'La mariée était en noir (1968)',
 'The Night of the Generals (1967)',
 'Le pacha (1968)',
 'Point Blank (1967)',
 'Le samouraï (1967)',
 'Wait Until Dark (1967)',
 'Ad ogni costo (1967)',
 'Bandolero! (1968)',
 'Bambai Raat Ki Bahon Mein (1968)',
 'The Boston Strangler (1968)',
 'The Brotherhood (1968)',
 'Burai yori daikanbu (1968)',
 'Deadfall (1968)',
 'Kôshikei (1968)',
 'Madigan (1968)',
 'She-Devils on Wheels (1968)',
 'Spalovac mrtvol (1969)',
 'The Split (1968)',
 'The Thomas Crown Affair (1968)',
 'Butch Cassidy and the Sundance Kid (1969)',
 'Le clan des Siciliens (1969)',
 'O Dragão da Maldade contra o Santo Guerreiro (1969)',
 'Misdaadjager Marlowe (1969)',
 'More (1969)',
 'Le passager de la pluie (1970)',
 'La piscine (1969)',
 'La sirène du Mississipi (1969)',
 'Taste of Excitement (1970)',
 'De wraak der wolven (1970)',
 'What Ever Happened to Aunt Alice? (1969)',
 'Z (1969)',
 'Bloody Mama (1970)',
 'Le cercle rouge (1970)',
 'Change of Habit (1969)',
 'Goodbye Gemini (1970)',
 'Indagine su un cittadino al di sopra di ogni sospetto (1970)',
 'Machine Gun McCain (1969)',
 'Un detective (1969)',
 'Performance (1970)',
 'Something for Everyone (1970)',
 'They Call Me Mister Tibbs! (1970)',
 'Un condé (1970)',
 '10 Rillington Place (1971)',
 'Big Jake (1971)',
 'Black Killer (1971)',
 'A Clockwork Orange (1971)',
 'De la part des copains (1970)',
 'The French Connection (1971)',
 'Sacco e Vanzetti (1971)',
 'De Cobra (1971)',
 'Straw Dogs (1971)',
 "Sweet Sweetback's Baadasssss Song (1971)",
 'Tang shan da xiong (1971)',
 "This Stuff'll Kill Ya! (1971)",
 'Villain (1971)',
 '$ (1971)',
 'Across 110th Street (1972)',
 'Black Mama, White Mama (1973)',
 'Boxcar Bertha (1972)',
 'The Valachi Papers (1972)',
 'Chandler (1971)',
 'Fear Is the Key (1972)',
 'Hammer (1972)',
 'Hickey &amp; Boggs (1972)',
 'The New Centurions (1972)',
 'Prime Cut (1972)',
 'Rivelazioni di un maniaco sessuale al capo della squadra mobile (1972)',
 'Sans sommation (1973)',
 'La scoumoune (1972)',
 'Super Fly (1972)',
 'Badge 373 (1973)',
 'Badlands (1973)',
 'Black Caesar (1973)',
 'Charley Varrick (1973)',
 'The Day of the Jackal (1973)',
 'Detroit 9000 (1973)',
 'The Don Is Dead (1973)',
 'Electra Glide in Blue (1973)',
 'Enter the Dragon (1973)',
 'The Friends of Eddie Coyle (1973)',
 'The Harder They Come (1972)',
 'Hell Up in Harlem (1973)',
 'Hiroshima shitô hen (1973)',
 'Jingi naki tatakai (1973)',
 'Lady Ice (1973)',
 'The Last of Sheila (1973)',
 'The Long Goodbye (1973)',
 'The Mack (1973)',
 'Mean Streets (1973)',
 'Milano trema: la polizia vuole giustizia (1973)',
 'The Offence (1973)',
 'Paper Moon (1973)',
 'Papillon (1973)',
 'Kaseki no mori (1973)',
 'Serpico (1973)',
 'The Seven-Ups (1973)',
 'The Sting (1973)',
 'The Stone Killer (1973)',
 'Walking Tall (1973)',
 'White Lightning (1973)',
 'Zanjeer (1973)',
 'Zinksärge für die Goldjungen (1973)',
 'Bring Me the Head of Alfredo Garcia (1974)',
 'Busting (1974)',
 'Cani arrabbiati (1974)',
 'Coonskin (1975)',
 'Death Wish (1974)',
 'The Marseille Contract (1974)',
 'Dirty Mary Crazy Larry (1974)',
 'The Gambler (1974)',
 'The Godfather: Part II (1974)',
 'Gone in 60 Seconds (1974)',
 'Jakob, der Lügner (1974)',
 'Jingi naki tatakai: Chojo sakusen (1974)',
 'Klansman (1974)',
 'The Longest Yard (1974)',
 'Lucky Luciano (1973)',
 'McQ (1974)',
 'Mr. Majestyk (1974)',
 'Murder on the Orient Express (1974)',
 'La polizia ha le mani legate (1975)',
 'Act of Vengeance (1974)',
 'The Sugarland Express (1974)',
 'The Take (1974)',
 'Thieves Like Us (1974)',
 'Thunderbolt and Lightfoot (1974)',
 'Deewaar (1975)',
 'Diamonds (1975)',
 'Dog Day Afternoon (1975)',
 'Faraar (1975)',
 'French Connection II (1975)',
 'Friday Foster (1975)',
 'Giliap (1975)',
 'Hard Times (1975)',
 'Hustle (1975)',
 'Johnny Firecloud (1975)',
 'Juego de amor prohibido (1975)',
 'Mitchell (1975)',
 'México, México, ra ra ra (1976)',
 'Nishaant (1975)',
 'The Jezebels (1975)',
 'Ransom (1974)',
 'Die verlorene Ehre der Katharina Blum (1975)',
 'The Yakuza (1974)',
 'Disco Godfather (1979)',
 'Gator (1976)',
 'Il grande racket (1976)',
 'The Killing of a Chinese Bookie (1976)',
 'Las Vegas Lady (1975)',
 'Mannen på taket (1976)',
 'Moi, Pierre Rivière, ayant égorgé ma mère, ma soeur et mon frère... (1976)',
 'Mr. Klein (1976)',
 'Roma a mano armata (1976)',
 'The Seven-Per-Cent Solution (1976)',
 'St. Ives (1976)',
 'Taxi Driver (1976)',
 'The Town That Dreaded Sundown (1976)',
 'Il trucido e lo sbirro (1976)',
 'The Amsterdam Kill (1977)',
 'Final Chapter: Walking Tall (1977)',
 'Les liens de sang (1978)',
 "Mort d'un pourri (1977)",
 'Rolling Thunder (1977)',
 'The Squeeze (1977)',
 'Sweeney! (1977)',
 'Telefon (1977)',
 'Tomorrow Never Comes (1978)',
 'Autostop rosso sangue (1977)',
 'Blue Collar (1978)',
 "The Brink's Job (1978)",
 'Death on the Nile (1978)',
 'Fingers (1978)',
 'Game of Death (1978)',
 'Midnight Express (1978)',
 'The Silent Partner (1978)',
 'Straight Time (1978)',
 "Who'll Stop the Rain (1978)",
 '...And Justice for All. (1979)',
 'Assassinio sul Tevere (1979)',
 'Buio Omega (1979)',
 'Escape from Alcatraz (1979)',
 'A Force of One (1979)',
 'Fukushû suru wa ware ni ari (1979)',
 'Going in Style (1979)',
 'The First Great Train Robbery (1978)',
 'La guerre des polices (1979)',
 'The Hollywood Strangler Meets the Skid Row Slasher (1979)',
 'I... comme Icare (1979)',
 'Malibu High (1979)',
 'The Onion Field (1979)',
 'Over the Edge (1979)',
 'Quadrophenia (1979)',
 'Scum (1979)',
 'Tom Horn (1980)',
 'When a Stranger Calls (1979)',
 'Yomigaeru kinrô (1979)',
 'American Gigolo (1980)',
 'Atlantic City (1980)',
 'Shinkansen daibakuha (1975)',
 'Defiance (1980)',
 'The Exterminator (1980)',
 'Gloria (1980)',
 'The Long Good Friday (1980)',
 'Luca il contrabbandiere (1980)',
 'Maniac (1980)',
 'Night of the Juggler (1980)',
 'Body Heat (1981)',
 'Butterfly (1982)',
 'Coup de torchon (1981)',
 "Cutter's Way (1981)",
 'Death Wish II (1982)',
 'Fort Apache the Bronx (1981)',
 'Garde à vue (1981)',
 'Ms. 45 (1981)',
 'Nightmare (1981)',
 'Pixote: A Lei do Mais Fraco (1981)',
 'The Postman Always Rings Twice (1981)',
 'Prince of the City (1981)',
 'Le professionnel (1981)',
 "Sharky's Machine (1981)",
 'Some Kind of Hero (1982)',
 'Thief (1981)',
 'True Confessions (1981)',
 'La balance (1982)',
 'Le battant (1983)',
 'The Border (1982)',
 'Class of 1984 (1982)',
 'The Concrete Jungle (1982)',
 'Monsignor (1982)',
 'Przesluchanie (1989)',
 'Shakti (1982)',
 'Still of the Night (1982)',
 'Vice Squad (1982)',
 'Die weiße Rose (1982)',
 '10 to Midnight (1983)',
 'Ardh Satya (1983)',
 "L'argent (1983)",
 'BMX Bandits (1983)',
 'Bad Boys (1983)',
 'The Big Score (1983)',
 'Blue Thunder (1983)',
 'Chained Heat (1983)',
 "Eddie Macon's Run (1983)",
 'Gorky Park (1983)',
 'Hammett (1982)',
 'Lone Wolf McQuade (1983)',
 'Le marginal (1983)',
 'The Outsiders (1983)',
 'Revenge of the Ninja (1983)',
 'Risky Business (1983)',
 'Scarface (1983)',
 'Streamers (1983)',
 'The Survivors (1983)',
 'Cento giorni a Palermo (1984)',
 'The Cotton Club (1984)',
 'Delitto al Blue Gay (1984)',
 'Exterminator 2 (1984)',
 'The Falcon and the Snowman (1985)',
 'Flashpoint (1984)',
 'Forbrydelsens element (1984)',
 'The Hit (1984)',
 'Once Upon a Time in America (1984)',
 'Slayground (1983)',
 "A Soldier's Story (1984)",
 'Streets of Fire (1984)',
 'Thief of Hearts (1984)',
 'After Hours (1985)',
 'Blastfighter (1984)',
 'Dance with a Stranger (1985)',
 'Death Wish 3 (1985)',
 'Détective (1985)',
 'The Holcroft Covenant (1985)',
 'No Retreat, No Surrender (1986)',
 'Police (1985)',
 'Pray for Death (1985)',
 "Prizzi's Honor (1985)",
 'Silverado (1985)',
 'Stick (1985)',
 'To Live and Die in L.A. (1985)',
 'Too Scared to Scream (1985)',
 'Witness (1985)',
 'Yasha (1985)',
 'Year of the Dragon (1985)',
 'At Close Range (1986)',
 'Band of the Hand (1986)',
 'Blue City (1986)',
 'The Boys Next Door (1985)',
 'Down by Law (1986)',
 'Mauvais sang (1986)',
 'Mona Lisa (1986)',
 "Murphy's Law (1986)",
 'Quicksilver (1986)',
 "River's Edge (1986)",
 'Shanghai Surprise (1986)',
 'Le solitaire (1987)',
 'Tenue de soirée (1986)',
 'Ying hung boon sik (1986)',
 'Anayurt Oteli (1987)',
 'The Believers (1987)',
 'Best Seller (1987)',
 'The Big Easy (1986)',
 'Cop (1988)',
 'Dead Aim (1987)',
 'Death Wish 4: The Crackdown (1987)',
 'Extreme Prejudice (1987)',
 'Heat (1986)',
 'Less Than Zero (1987)',
 'Lung foo fong wan (1987)',
 'Nayakan (1987)',
 'Near Dark (1987)',
 "No Man's Land (1987)",
 'No Way Out (1987)',
 'The Pick-up Artist (1987)',
 'The Principal (1987)',
 'Raising Arizona (1987)',
 'Someone to Watch Over Me (1987)',
 'Street Smart (1987)',
 'Suspect (1987)',
 'The Untouchables (1987)',
 'Wall Street (1987)',
 'Wanted: Dead or Alive (1986)',
 'Ying hung boon sik II (1987)',
 'Above the Law (1988)',
 'The Accused (1988)',
 'Agni Natchathiram (1988)',
 'Appointment with Death (1988)',
 'Assa (1988)',
 'Colors (1988)',
 'Frantic (1988)',
 'Hero and the Terror (1988)',
 'Huo wu feng yun (1988)',
 'Kholodnoe leto pyatdesyat tretego (1987)',
 'Krótki film o zabijaniu (1988)',
 'Kárhozat (1988)',
 'Mississippi Burning (1988)',
 'PS sista sommaren (1988)',
 'Prison (1988)',
 'Running on Empty (1988)',
 'Salaam Bombay! (1988)',
 'Seven Hours to Judgment (1988)',
 'Shakedown (1988)',
 'Tequila Sunrise (1988)',
 'The Thin Blue Line (1988)',
 'Things Change (1988)',
 'Wong gok ka moon (1988)',
 'Young Guns (1988)',
 'Casualties of War (1989)',
 'Citizen Tania (1989)',
 'The Cook, the Thief, His Wife & Her Lover (1989)',
 'Dead Bang (1989)',
 'Dip huet seung hung (1989)',
 'Dom za vesanje (1988)',
 'Drugstore Cowboy (1989)',
 'Family Business (1989)',
 'Harlem Nights (1989)',
 'Heathers (1988)',
 'An Innocent Man (1989)',
 'Johnny Handsome (1989)',
 'Kinjite: Forbidden Subjects (1989)',
 'Lock Up (1989)',
 'Melancholia (1989)',
 'The Mighty Quinn (1989)',
 'Monsieur Hire (1989)',
 'Mystery Train (1989)',
 'One Man Force (1989)',
 'The Package (1989)',
 'La petite voleuse (1988)',
 'The Punisher (1989)',
 'Romero (1989)',
 'Sea of Love (1989)',
 'Sono otoko, kyôbô ni tsuki (1989)',
 'True Believer (1989)',
 'Turner & Hooch (1989)',
 'Aaj Ka Arjun (1990)',
 'After Dark, My Sweet (1990)',
 'Agneepath (1990)',
 'Bad Influence (1990)',
 'Blue Steel (1989)',
 'Desperate Hours (1990)',
 'The Godfather: Part III (1990)',
 'Goodfellas (1990)',
 'The Grifters (1990)',
 'Hard to Kill (1990)',
 'Heart Condition (1990)',
 'Henry: Portrait of a Serial Killer (1986)',
 'The Hot Spot (1990)',
 'Huo shao dao (1990)',
 'Impulse (1990)',
 'Internal Affairs (1990)',
 'The Krays (1990)',
 'The Last of the Finest (1990)',
 'Miami Blues (1990)',
 "Miller's Crossing (1990)",
 'Music Box (1989)',
 'Nightbreed (1990)',
 'Q &amp; A (1990)',
 'Revenge (1990)',
 'Rodrigo D: No futuro (1990)',
 'State of Grace (1990)',
 'Tridev (1989)',
 'The Two Jakes (1990)',
 'Átame! (1990)',

In [319]:
reviews['user_id'].unique()

array([    1,     2,     3, ..., 53966, 53967, 53968], dtype=int64)

In [353]:
reviews[reviews['user_id']==1].sort_values(['rating'], ascending=False)

,user_id,movie_id,rating,timestamp,date,month_1,month_2,month_3,month_4,month_5,...,month_9,month_10,month_11,month_12,year_2013,year_2014,year_2015,year_2016,year_2017,year_2018
0,1,68646,10,1381620027,2013-10-12 23:20:27,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
1,1,113277,10,1379466669,2013-09-18 01:11:09,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [31]:
def make_recs():
    '''
    INPUT
    None
    OUTPUT
    recs - a dictionary with keys of the user and values of the recommendations
    '''
    # Create dictionary to return with users and ratings
    recs = dict()
    
    # How many users for progress bar
    
    
    # Create the progressbar

    # unique users
    unique_users = reviews['user_id'].unique()
    
    # For each user
    for user in unique_users:
        # create empty list to store similar movies for the user
        similar_movies = list()
        
        # Update the progress bar

        # Pull only the reviews the user has seen
        seen_movies = reviews[reviews['user_id']==user]
        seen_movies = list(seen_movies.sort_values(['rating'], ascending=False)['movie_id'])

        # Look at each of the movies (highest ranked first), 
        for movie in seen_movies:
        # pull the movies the user hasn't seen that are most similar
            similar_movies.extend(find_similar_movies(movie))
        
        # These will be the recommendations - continue until 10 recs 
        # or you have depleted the movie list for the user
            
            if len(similar_movies) > 10:
                break

        if len(similar_movies) != 0:
            similar_movies = similar_movies[:10]

        # add to dictionary user with associated similar movies
        recs[user] = similar_movies
            
    # finish the progress bar

    
    return recs

In [32]:
recs = make_recs()

In [390]:
print([1,2].extend([3,4]))

None

In [347]:
similar_movies

array([3, 3, 3, ..., 0, 0, 0], dtype=int64)

In [42]:
recs[1]

["Fantômas - À l'ombre de la guillotine (1913)",
 'Regeneration (1915)',
 'Schloß Vogeloed (1921)',
 'The Lodger: A Story of the London Fog (1927)',
 'Underworld (1927)',
 'Die Büchse der Pandora (1929)',
 'The Docks of New York (1928)',
 'The Big House (1930)',
 'Escape! (1930)',
 'Hogaraka ni ayume (1930)']

### How Did We Do?

Now that you have made the recommendations, how did we do in providing everyone with a set of recommendations?

`4.` Use the cells below to see how many individuals you were able to make recommendations for, as well as explore characteristics about individuals for whom you were not able to make recommendations.

In [49]:
# Explore recommendations
users_10 = list()
users_less_than_10 = list()
users_no = list()

for key, value in recs.items():
    if len(value) == 10:
        users_10.append(key)
    elif (len(value) > 0 & len(value) < 10):
        users_less_than_10.append(key)
    else:
        users_no.append(key)

In [52]:
print('Total number of users is {}'.format(len(reviews['user_id'].unique())))
print('Number of users with 10 recommendations is {}'.format(len(users_10)))
print('Number of users with less than 10 recommendations is {}'.format(len(users_less_than_10)))
print('Number of users with no recommendation is {}'.format(len(users_no)))

Total number of users is 53968
Number of users with 10 recommendations is 51792
Number of users with less than 10 recommendations is 2002
Number of users with no recommendation is 174

In [55]:
# Some characteristics of my content based recommendations
users_without_all_recs = users_less_than_10 #store user ids without recs
users_with_all_recs = users_10 # users with all recs here
no_recs = users_no # users with no recommendations

print("There were {} users without all 10 recommendations we would have liked to have.".format(len(users_without_all_recs)))
print("There were {} users with all 10 recommendations we would like them to have.".format(len(users_with_all_recs)))
print("There were {} users with no recommendations at all!".format(len(no_recs)))

There were 2002 users without all 10 recommendations we would have liked to have.
There were 51792 users with all 10 recommendations we would like them to have.
There were 174 users with no recommendations at all!

In [56]:
# Closer look at individual user characteristics - this may help it was from an earlier notebook
user_items = reviews[['user_id', 'movie_id', 'rating']]
user_by_movie = user_items.groupby(['user_id', 'movie_id'])['rating'].max().unstack()

def movies_watched(user_id):
    '''
    INPUT:
    user_id - the user_id of an individual as int
    OUTPUT:
    movies - an array of movies the user has watched
    '''
    movies = user_by_movie.loc[user_id][user_by_movie.loc[user_id].isnull() == False].index.values

    return movies


movies_watched(189)

array([457430], dtype=int64)

In [58]:
# should have 0 similar movies?
find_similar_movies(457430)

[]

In [59]:
movies[movies['movie_id']==457430]

,movie_id,movie,genre,date,1800's,1900's,2000's,History,News,Horror,...,Fantasy,Romance,Game-Show,Action,Documentary,Animation,Comedy,Short,Western,Thriller
13745,457430,El laberinto del fauno (2006),Drama|Fantasy|War,2006,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
# More exploring
print("Some of the movie lists for users without any recommendations include:")
# Just one of many questions you could continue exploring...

### Now What?  

Well, if you were really strict with your criteria for how similar two movies are (like I was initially), then you still have some users that don't have all 10 recommendations (and a small group of users who have no recommendations at all). 

As stated earlier, recommendation engines are a bit of an **art** and a **science**.  There are a number of things we still could look into - how do our collaborative filtering and content based recommendations compare to one another? How could we incorporate user input along with collaborative filtering and/or content based recommendations to improve any of our recommendations?  How can we truly gain recommendations for every user?

`5.` In this last step feel free to explore any last ideas you have with the recommendation techniques we have looked at so far.  You might choose to make the final needed recommendations using the first technique with just top ranked movies.  You might also loosen up the strictness in the similarity needed between movies.  Be creative and share your insights with your classmates!

In [ ]:
# Cells for exploring